on:
    push:
    workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: test
          id: test
          uses: ./
          with:
            id_of_input: 'input value 1'
            id_of_input2: 'input value 2'
        - name: view result
          run: |
            echo ${{ env.id_of_output }}
            echo ${{ env.id_of_output2 }}
          env:
            id_of_output: ${{ steps.test.outputs.id_of_output }}
            id_of_output2: echo ${{ steps.test.outputs.id_of_output2 }}